trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'

steps:
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.4.1'
    inputs:
      versionSpec: 4.4.1

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      restoreSolution: '**/*.sln'

  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis configuration'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'loic-lopez'
      scannerMode: 'MSBuild'
      projectKey: 'loic-lopez_UMVC'
      projectName: 'UMVC Model-View-Controller Generator built for Unity'


  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    inputs:
      solution: 'UMVC.Core/UMVC.Core.sln'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
        **\$(BuildConfiguration)\*Test*.dll
        !**\obj\**
      codeCoverageEnabled: true
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

  - task: SonarCloudAnalyze@1
    displayName: 'Run SonarCloud analysis'

  - task: SonarCloudPublish@1
    displayName: 'Publish results on build summary'