name: UMVC.Editor Tests

on:
  push:
    branches:
      - master
      - release/*
      - staging/*
      - pre-release/*
  pull_request:
    branches: [ master ]
    
#env:
#  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  test:
    name: Test UMVC.Editor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion:
          - 2019.3.12f1
        targetPlatform:
          - StandaloneWindows64
        testMode:
          - editmode
    steps:
      - uses: actions/checkout@v2

      # Set the UNITY_LICENSE environment variable
      - name: Setup license
        # This step:
        #   - Grabs the license file contents from the $LICENSE_FILE_PATH
        #   - Uses substitution to escape newline characters for GitHub Actions set-env.
        #     (from: https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/td-p/37870)
        #   - Set the UNITY_LICENSE env var for all future steps using special GitHub Actions syntax
        env:
          LICENSE_FILE_PATH: ./Licences/Unity_v2019.x.ulf
        run: |
          license=$(<"$LICENSE_FILE_PATH")
          license="${license//'%'/'%25'}"
          license="${license//$'\n'/'%0A'}"
          license="${license//$'\r'/'%0D'}"
          echo "::set-env name=UNITY_LICENSE::$license"
      # Delete unity version file (test runner will crash otherwise)
      - name: Delete ProjectVersion.txt
        run: sudo rm ./${{ matrix.projectPath }}/ProjectSettings/ProjectVersion.txt


      # Run tests - only edit mode supported
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.5
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: ./testReports/${{ matrix.targetPlatform }}
          testMode: editmode
  
