name: UMVC.Core

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Test:
    name: Test UMVC.Core 🧪
    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
      - uses: actions/setup-java@v3  # Used for sonarcloud scanner
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15

      - name: Start SonarCloud scanner for UMVC.Core
        run: >
          dotnet sonarscanner begin /k:"UMVC.Core" `
            /o:"loic-lopez" `
            /n:"UMVC.Core" `
            /v:"${{ steps.gitversion.outputs.semVer }}" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN_CORE }}" `
            /d:sonar.cs.vscoveragexml.reportsPaths="UMVC.Core/coverage.xml" `
            /d:sonar.scm.provider=git `
            /d:sonar.projectDescription="UMVC.Core - Model-View-Controller Base classes for UMVC" `
            /d:sonar.host.url=https://sonarcloud.io /d:sonar.verbose=true `

      - name: Test UMVC.Core
        run: dotnet-coverage collect 'dotnet test UMVC.Core/UMVC.Core.sln' -f xml -o 'UMVC.Core/coverage.xml'

      - name: End SonarCloud scanner for UMVC.Core
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN_CORE }}"
          
  Build:
    name: Build UMVC.Core 🏗️
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Install dotnet dependencies
        run: dotnet restore ./UMVC.Core/UMVC.Core.sln

      - name: Build
        run: dotnet build ./UMVC.Core/UMVC.Core.sln --configuration Release
        
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Components.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Components/bin/Release/net48/UMVC.Core.Components.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Generation.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Generation/bin/Release/net48/UMVC.Core.Generation.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Templates.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Templates/bin/Release/net48/UMVC.Core.Templates.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.MVC.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/MVC/bin/Release/net48/UMVC.Core.MVC.dll
  