name: UMVC.Editor Tests

on:
  push:
    branches:
      - master
      - release/*
      - staging/*
      - pre-release/*
  pull_request:
    branches: [ master ]
    
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  test:
    name: Test UMVC.Editor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testMode:
          - editmode
    steps:
      - uses: actions/checkout@v2
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          unityVersion: 2019.3.13f1
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
  
