name: UMVC.Editor Tests

on:
  push:
    branches:
      - master
      - release/*
      - staging/*
      - pre-release/*
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: Test UMVC.Editor
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.13f1
    steps:
      - uses: actions/checkout@v2

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      # Activate unity
      - name: Activate Unity
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      - name: Run tests
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -runTests -testPlatform editmode
#  
