name: UMVC.Editor

# Ref: https://gist.github.com/chatrat12/9780fffe59bc46a63bc0b9b665489e08

on:
  push:
    branches:
      - master
      - release/*
      - staging/*
      - pre-release/*
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.13f1
    steps:
      - name: Extract Branch Name
        
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        if: contains(github.ref, "master")
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build
          ref: ${{ github.sha }}

      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        if: !contains(github.ref, "master")
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: actions/checkout@v2

          
      - name: Is UMVC.Core failing? 
        if: ${{ steps.wait-for-build.outputs.conclusion == 'failure' }} 
        run: ">&2 echo 'There is a problem with your UMVC.Core build!\\n Exiting!!' && exit 1"

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      # Activate unity
      - name: Activate Unity
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      # Run tests
      - name: Run tests
        run: xvfb-run /opt/Unity/Editor/Unity -quit -batchmode -nographics -logFile -runTests -testPlatform editmode
#  
