name: UMVC.Core

on:
  pull_request:
    branches: [ master ]

jobs:
  Test:
    name: Test UMVC.Core 🧪
    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Install dotnet dependencies
        run: dotnet restore ./UMVC.Core/UMVC.Core.sln

      - name: Build
        run: dotnet build ./UMVC.Core/UMVC.Core.sln --configuration Debug

      - name: Test
        run: .\UMVC.Core\packages\OpenCover\4.7.1221\tools\OpenCover.Console.exe -register -filter:"+[*]* -[*]*.Templates.* -[*]*.Mock.*" -target:".\UMVC.Core\packages\NUnit.ConsoleRunner\3.12.0\tools\nunit3-console.exe" -targetargs:"/domain:single .\UMVC.Core\Tests\bin\Debug\net48\UMVC.Core.Tests.dll" -output:coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          
  Build:
    name: Build UMVC.Core 🏗️
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Install dotnet dependencies
        run: dotnet restore ./UMVC.Core/UMVC.Core.sln

      - name: Build
        run: dotnet build ./UMVC.Core/UMVC.Core.sln --configuration Release
        
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Components.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Components/bin/Release/net48/UMVC.Core.Components.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Generation.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Generation/bin/Release/net48/UMVC.Core.Generation.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.Templates.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/Templates/bin/Release/net48/UMVC.Core.Templates.dll
          
      - uses: actions/upload-artifact@v3
        name: Upload UMVC.Core.MVC.dll
        with:
          name: UMVC.Core.Build
          path: UMVC.Core/MVC/bin/Release/net48/UMVC.Core.MVC.dll
  